
openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      description: Returns a list of users.
    post:
      summary: Create a user
      description: Adds a new user to the database.
  /users/{id}:
    get:
      summary: Get user by ID
      description: Returns a single user.
    delete:
      summary: Delete a user
      description: Removes a user by ID.
