openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      description: Returns a list of all users.
    post:
      summary: Create a user
      description: Adds a new user to the database.
  /users/{id}:
    get:
      summary: Get user by ID
      description: Returns a specific user by their ID.
    put:
      summary: Update user
      description: Updates user details by ID.
    delete:
      summary: Delete user
      description: Deletes a user by ID.
